import type { DepartmentCode } from '@/lib/zones/departments'

// Las localidades del interior, del listado público de OSE publicado en catalogodatos.gub.uy
// (consultado el 2026-09-19), tomando las que concentran población y corrigiendo su ortografía: la
// fuente viene en mayúsculas y sin acentos, y una lista que sugiere «Tacuarembo» se nota.
//
// Es una ayuda para escribir, **no** una restricción (FR-019): lo que no esté acá se escribe igual
// y se guarda tal cual. Por eso una lista curada de lo que la gente usa vale más que una lista
// completa mal escrita. Se amplía cuando alguien reporte que le falta la suya.
export const INTERIOR_LOCALITIES: Readonly<
  Record<Exclude<DepartmentCode, 'UY-MO'>, readonly string[]>
> = {
  'UY-AR': ['Artigas', 'Bella Unión', 'Tomás Gomensoro', 'Baltasar Brum', 'Sequeira', 'Cuaró'],
  'UY-CA': [
    'Canelones',
    'Las Piedras',
    'Ciudad de la Costa',
    'Pando',
    'Santa Lucía',
    'Progreso',
    'La Paz',
    'Barros Blancos',
    'Toledo',
    'Sauce',
    'Atlántida',
    'Parque del Plata',
    'Salinas',
    'Solymar',
    'Lagomar',
    'Shangrilá',
    'El Pinar',
    'Paso Carrasco',
    'Joaquín Suárez',
    'Empalme Olmos',
    'Los Cerrillos',
    'Tala',
    'San Ramón',
    'San Jacinto',
    'Migues',
    'Santa Rosa',
    'Villa Aeroparque',
  ],
  'UY-CL': ['Melo', 'Río Branco', 'Fraile Muerto', 'Isidoro Noblía', 'Aceguá', 'Tupambaé'],
  'UY-CO': [
    'Colonia del Sacramento',
    'Carmelo',
    'Juan Lacaze',
    'Nueva Helvecia',
    'Rosario',
    'Tarariras',
    'Nueva Palmira',
    'Ombúes de Lavalle',
    'Colonia Valdense',
  ],
  'UY-DU': ['Durazno', 'Sarandí del Yí', 'Villa del Carmen', 'La Paloma', 'Carlos Reyles'],
  'UY-FS': ['Trinidad', 'Ismael Cortinas', 'Andresito'],
  'UY-FD': ['Florida', 'Sarandí Grande', 'Casupá', 'Fray Marcos', 'Cardal', '25 de Mayo'],
  'UY-LA': ['Minas', 'José Pedro Varela', 'Solís de Mataojo', 'Mariscala', 'Batlle y Ordóñez'],
  'UY-MA': [
    'Maldonado',
    'Punta del Este',
    'San Carlos',
    'Piriápolis',
    'Pan de Azúcar',
    'Aiguá',
    'Solís',
    'La Barra',
    'Manantiales',
    'José Ignacio',
    'Balneario Buenos Aires',
  ],
  'UY-PA': ['Paysandú', 'Guichón', 'Quebracho', 'Porvenir', 'Tambores', 'Chapicuy'],
  'UY-RN': ['Fray Bentos', 'Young', 'Nuevo Berlín', 'San Javier'],
  'UY-RV': ['Rivera', 'Tranqueras', 'Vichadero', 'Minas de Corrales'],
  'UY-RO': [
    'Rocha',
    'Chuy',
    'Castillos',
    'La Paloma',
    'Lascano',
    'Velázquez',
    'Cebollatí',
    'La Pedrera',
    'Punta del Diablo',
    'Aguas Dulces',
    'Barra de Valizas',
    '18 de Julio',
  ],
  'UY-SA': ['Salto', 'Constitución', 'Belén', 'Villa Constitución', 'Termas del Daymán'],
  'UY-SJ': [
    'San José de Mayo',
    'Ciudad del Plata',
    'Libertad',
    'Rodríguez',
    'Ecilda Paullier',
    'Puntas de Valdez',
    'Kiyú',
  ],
  'UY-SO': ['Mercedes', 'Dolores', 'Cardona', 'Palmitas', 'Villa Soriano', 'José Enrique Rodó'],
  'UY-TA': ['Tacuarembó', 'Paso de los Toros', 'San Gregorio de Polanco', 'Ansina', 'Curtina'],
  'UY-TT': [
    'Treinta y Tres',
    'Vergara',
    'Santa Clara de Olimar',
    'Cerro Chato',
    'José Pedro Varela',
  ],
}
