// Los barrios de Montevideo, de la capa oficial de la Intendencia (`ide:limites_barrios`,
// consultada el 2026-09-19), escritos como los dice la gente en vez de como los codifica el
// sistema de información geográfica: ahí «Pocitos» convive con «PQUE BATLLE VILLA DOLORES».
//
// Montevideo va aparte del resto del país porque su fuente es otra: en la lista nacional de
// localidades, Montevideo entero es **una sola entrada**, y sin estos barrios la mitad del padrón
// quedaría sin zona utilizable.
export const MONTEVIDEO_BARRIOS = [
  'Aguada',
  'Aires Puros',
  'Atahualpa',
  'Bañados de Carrasco',
  'Barrio Sur',
  'Bella Italia',
  'Bella Vista',
  'Belvedere',
  'Bolívar',
  'Brazo Oriental',
  'Buceo',
  'Capurro',
  'Carrasco',
  'Carrasco Norte',
  'Casabó',
  'Casavalle',
  'Castro',
  'Centro',
  'Cerrito de la Victoria',
  'Cerro',
  'Ciudad Vieja',
  'Colón',
  'Conciliación',
  'Cordón',
  'Flor de Maroñas',
  'Ituzaingó',
  'Jacinto Vera',
  'Jardines del Hipódromo',
  'La Blanqueada',
  'La Comercial',
  'La Figurita',
  'La Paloma',
  'La Teja',
  'Larrañaga',
  'Las Acacias',
  'Las Canteras',
  'Lezica',
  'Malvín',
  'Malvín Norte',
  'Manga',
  'Maroñas',
  'Melilla',
  'Mercado Modelo',
  'Nuevo París',
  'Pajas Blancas',
  'Palermo',
  'Parque Batlle',
  'Parque Rodó',
  'Paso de la Arena',
  'Paso de las Duranas',
  'Peñarol',
  'Piedras Blancas',
  'Pocitos',
  'Prado',
  'Puerto',
  'Punta Carretas',
  'Punta Gorda',
  'Punta Rieles',
  'Reducto',
  'Sayago',
  'Tres Cruces',
  'Tres Ombúes',
  'Unión',
  'Villa Dolores',
  'Villa Española',
  'Villa García',
  'Villa Muñoz',
] as const
